// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test, Vm} from "forge-std/Test.sol";
import {HecateSettlementVerifier} from "../HecateSettlementVerifier.sol";

/**
 * @title HecateSettlementVerifier.t.sol
 * @notice Forge tests for the v1 on-chain engine-signature verifier.
 *
 * The fixture (HASH, SIG, ENGINE) is generated by
 *   npx tsx scripts/gen-onchain-fixture.ts
 *
 * It is deterministic: hashBatchReceiptBody is canonical-JSON, signHash is
 * RFC 6979 deterministic ECDSA, and every field of the body is hard-coded
 * in the generator. To regenerate, run the script and paste the three
 * constants below verbatim.
 */
contract HecateSettlementVerifierTest is Test {
    HecateSettlementVerifier verifier;

    // Generated by scripts/gen-onchain-fixture.ts
    // Body source: contrived deterministic body
    bytes32 internal constant HASH =
        0x7742e4f98d8ba373221d69c84ead0925a4b801168a4f53bbf8deeb6fd3a1216e;
    bytes   internal constant SIG =
        hex"21545b09e8f746242e94d0029d572bb3a9e4f0a8155f56fafc8662a2df6efd99537a7b5a6be37f3eb3b784d6f905d549c0633f1f1dd44169402ad23abf436ec61c";
    address internal constant ENGINE = 0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf;

    function setUp() public {
        verifier = new HecateSettlementVerifier();
    }

    function test_verifyHonestReceipt() public view {
        bool ok = verifier.verifyEngineSignature(HASH, SIG, ENGINE);
        assertTrue(ok, "honest fixture must verify");
    }

    function test_recoverSignerReturnsEngine() public view {
        address signer = verifier.recoverSigner(HASH, SIG);
        assertEq(signer, ENGINE, "recovered signer must match engine");
    }

    function test_rejectsWrongEngine() public view {
        address wrong = address(uint160(uint256(keccak256("wrong-engine"))));
        bool ok = verifier.verifyEngineSignature(HASH, SIG, wrong);
        assertFalse(ok, "wrong expectedEngine must not verify");
    }

    function test_rejectsTamperedHash() public view {
        bytes32 tampered = bytes32(uint256(HASH) ^ 1);
        bool ok = verifier.verifyEngineSignature(tampered, SIG, ENGINE);
        assertFalse(ok, "flipped hash bit must not verify");
    }

    function test_rejectsTamperedSignature() public view {
        bytes memory tampered = SIG;
        tampered[0] = bytes1(uint8(tampered[0]) ^ 0x01);
        bool ok = verifier.verifyEngineSignature(HASH, tampered, ENGINE);
        assertFalse(ok, "flipped signature byte must not verify");
    }

    function test_rejectsBadLengthSignature() public view {
        bytes memory short = hex"00";
        address signer = verifier.recoverSigner(HASH, short);
        assertEq(signer, address(0), "short signature must return zero");
    }

    function test_rejectsZeroExpectedEngine() public view {
        bool ok = verifier.verifyEngineSignature(HASH, SIG, address(0));
        assertFalse(ok, "address(0) expectedEngine must not verify");
    }

    function test_verifyAndEmitEmitsEvent() public {
        vm.recordLogs();
        bool ok = verifier.verifyAndEmit(HASH, SIG, ENGINE);
        assertTrue(ok);
        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 1, "exactly one event");
        // event ReceiptVerified(bytes32 indexed hash, address indexed signer)
        assertEq(logs[0].topics[0], keccak256("ReceiptVerified(bytes32,address)"));
        assertEq(logs[0].topics[1], HASH);
        assertEq(logs[0].topics[2], bytes32(uint256(uint160(ENGINE))));
    }

    function test_verifyAndEmitNoEventOnFailure() public {
        vm.recordLogs();
        bool ok = verifier.verifyAndEmit(HASH, SIG, address(0xDEAD));
        assertFalse(ok);
        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 0, "no event on failed verification");
    }
}
