/**
 * Generate a deterministic on-chain verification fixture.
 *
 * Builds a contrived BatchReceiptBody whose every field is fixed, hashes it
 * via the same canonical-JSON path the engine uses, signs with the dev key
 * 0x...01, and prints Solidity constants ready to paste into
 *   contracts/test/HecateSettlementVerifier.t.sol
 *
 * The fixture is deterministic because:
 *   - every body field is hard-coded
 *   - hashBatchReceiptBody uses canonical JSON (deterministic by spec)
 *   - signHash uses RFC 6979 deterministic ECDSA via @noble/secp256k1
 *
 * Optional flag:
 *   --bundle <path>   pull the body hash + signature from a saved bundle
 *                     (output of `npm run simulate -- --save-bundle ...`)
 *                     instead of the contrived deterministic body.
 *
 * Usage:
 *   npx tsx scripts/gen-onchain-fixture.ts
 *   npx tsx scripts/gen-onchain-fixture.ts --bundle ./data/last-bundle.json
 */

import { readFile } from "node:fs/promises";
import {
  hashBatchReceiptBody,
  signHash,
  privateKeyToAddress,
  recoverHashSigner
} from "@shared/crypto";
import type { BatchReceiptBody, Hex32, Hex65 } from "@shared/schemas";

const DEV_PK = ("0x" + "0".repeat(63) + "1") as Hex32;

const ZERO32 = ("0x" + "0".repeat(64)) as Hex32;

const CONTRIVED_BODY: BatchReceiptBody = {
  batch_id: "batch_onchain_fixture_v1",
  market: "ETH/USDC",
  matching_rule: "UNIFORM_CLEARING_PRICE_V1",
  intent_envelope_root: ZERO32,
  private_payload_commitment_root: ZERO32,
  vault_state_before_hash: ZERO32,
  vault_state_after_hash: ZERO32,
  reservation_book_before_hash: ZERO32,
  reservation_book_after_hash: ZERO32,
  settlement_hash: ZERO32,
  num_intents: 0,
  num_matched: 0,
  clearing_price: "0",
  timestamp_ms: 1_700_000_000_000,
  runtime: {
    runtime_mode: "LOCAL_MOCK",
    engine_code_digest: "sha256:dev-local",
    eigencompute_app_id: null,
    eigencompute_image_digest: null,
    eigencompute_attestation_id: null
  }
};

async function fromBundle(path: string): Promise<{
  hash: Hex32;
  sig: Hex65;
  engine: string;
}> {
  const raw = await readFile(path, "utf-8");
  const bundle = JSON.parse(raw);
  const br = bundle.batchReceipt;
  if (!br || !br.engine_signature) {
    throw new Error("bundle missing batchReceipt or engine_signature");
  }
  const { engine_signature, ...body } = br;
  const hash = hashBatchReceiptBody(body);
  return {
    hash,
    sig: engine_signature as Hex65,
    engine: bundle.expectedEngineAddress
  };
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  let bundlePath: string | undefined;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--bundle") {
      bundlePath = args[++i];
    }
  }

  let hash: Hex32;
  let sig: Hex65;
  let engine: string;

  if (bundlePath) {
    const r = await fromBundle(bundlePath);
    hash = r.hash;
    sig = r.sig;
    engine = r.engine;
  } else {
    hash = hashBatchReceiptBody(CONTRIVED_BODY);
    sig = signHash(hash, DEV_PK);
    engine = privateKeyToAddress(DEV_PK);
  }

  // Sanity: recovery must agree with the published engine.
  const recovered = recoverHashSigner(hash, sig);
  if (recovered !== engine) {
    throw new Error(
      `internal sanity failed: recovered ${recovered} != engine ${engine}`
    );
  }

  // Solidity-pasteable form. SIG body is hex without the 0x prefix.
  console.log(`// Generated by scripts/gen-onchain-fixture.ts`);
  console.log(`// Body source: ${bundlePath ?? "contrived deterministic body"}`);
  console.log(`bytes32 internal constant HASH   = ${hash};`);
  console.log(`bytes   internal constant SIG    = hex"${sig.slice(2)}";`);
  console.log(`address internal constant ENGINE = ${engine};`);
}

main().catch((e) => {
  console.error(`error: ${(e as Error).message}`);
  process.exit(1);
});
